# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DamannaFront' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DamannaFront
  pod "StompClientLib"
  pod "MessageKit"
end
